### ISSUE TITLE
Timesheet entries marked as exported by users without permission

### ISSUE THREAD

**Issue by rbuehler-teletrend** [kimai/kimai#4679] opened 2024-03-05 15:17 UTC
### Describe the issue

For normal users we have following roles disabled: edit_exported_timesheet, edit_export_other_timesheet, edit_export_own_timesheet.
That normal user however, is intentionally allowed to export own and other timesheets (create_export, export_other_timesheet, export_own_timesheet are allowed).

Although the user should not be able to edit the export settings, after export those timesheet entries are marked as exported.
Additionally, there is no entry in the audit log about this change. Only manual changes of the timesheet entry are logged.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.12.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment] 2024-03-06 21:15
???

You allow to switch the export flag and then open a bug that the export flag can be switched?

These are dangerous permissions: create_export, export_other_timesheet, export_own_timesheet

**Comment by rbuehler-teletrend** [comment] 2024-03-07 08:44
Hi Kevin

I just see the difference between Kimai 1 and 2 where I think, in Kimai 1 the "mark as exported" checkbox is by default disabled and in Kimai 2 it is by default enabled. Anyhow, the standard user without edit_export_* permissions doesn't see this option, therefore it was never a problem in the past - there was no way for a standard user to change the export flag.

I'd wish that a standard user can create an export from the export menu but without changing the export flag.
This was / would be useful, if a standard user wants to give an overview to a customer about the progress of a project.
Yes, you could do that through the export of timesheets if export_*_timesheet permissions are given. It even doesn't change the export flag.
But here the possibilities to export are limited and you can't select from various (even custom) PDF's for example.

One option could be to not include the permission to change the exported flag into create_export and add it as a separate permission.
Or to change the default in the export menu back to not mark as exported.
If this default is defined somewhere in the database, I would also be happy to know where to change it.

**Comment by kevinpapst** [comment] 2024-03-10 13:33
Duplicate of #4339

> I'd wish that a standard user can create an export from the export menu but without changing the export flag.

 It was never meant to be used by regular users. But anyway: I understand!

Can you post your comment in the older issue please (and vote for it).

**Closed as not planned by kevinpapst** 2024-03-10 13:33 UTC
Labels: bug, duplicate
