### ISSUE TITLE
Translation license(s)

### ISSUE THREAD

**Issue by comradekingu** [kimai/kimai#3795] opened 2023-01-26 14:16 UTC
### Describe the issue

https://hosted.weblate.org/projects/kimai/#information says AGPLv3-or-later for the wizard component,
and AGPLv3-only for most everything else.
https://github.com/kimai/kimai says AGPLv3-or-later.

This seems to be an error.

Can be changed to AGPLv3+ in https://hosted.weblate.org/settings/kimai/respective-component/ for each one.
"kingu" isn't an admin, so I can't do it.

Moreover, there are some MIT-licensed components, for the glossary, website and such.
Why not make everything AGPLv3+?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.xx.xx

### How do you run Kimai?

Other (please mention below)

### Which PHP version are you using?

Unknown

### Screenshots

![bilde](https://user-images.githubusercontent.com/13802408/214857759-55644e1f-8354-49a0-95a3-6f46b908bbd6.png)
![bilde](https://user-images.githubusercontent.com/13802408/214857870-2df21fbd-056e-4a7a-a817-1af44bcc7ca3.png)

**Comment by kevinpapst** [comment] 2023-01-26 16:16
Well spotted. The labels at Weblate did not show any difference, so I didn't notice that I have clicked the wrong one.

Changed them all to "3 or later" now.

Well, not all, because 2 components are still "MIT".

The "Theme" component relates to a MIT licensed repository, basically the theme of Kimai which I want to be MIT licensed.

And I don't even know what the Glossary is, I mean I know what a Glossary is, but I have neither created nor ever used it in Weblate. Not sure what to do with this one. Any recommendations?

**Comment by kevinpapst** [comment] 2023-01-26 16:48
While we are talking, I have a question and maybe you have an answer, as you know Weblate much better than me:
do you know what might be causing this "rollback" of all translations of one key?

This PR #3791 changes all keys with `<source>download</source>` back to the base/english translation:
https://github.com/kimai/kimai/pull/3791/files#diff-7db923121ceaf14dbc1e8318d482b9dd5a0784248d3536a9339bc03cc2e52611R87

Could that be caused by a Weblate extension? 
I recently activated the extension [Add missing languages](https://docs.weblate.org/en/latest/admin/addons.html#addon-weblate-consistency-languages), but I don't see why that should cause this behavior.

**Comment by comradekingu** [comment] 2023-01-26 17:55
https://hosted.weblate.org/projects/kimai/glossary/ is the glossary.
It can be used to either avoid erroneous translations, or require correct translations.
Seems like some languages use it on their own accord, but it is also possible to add terms to the source language, that in turn propagate to all of them.
Keep it and AGPLv3+ it. Can go through and explain the terms, or add the ones that are actually thought to be problematic.

Is it possible to dual-license the theme and keep it AGPLv3+ for Kimai? I think it effectively becomes that with full and strong copyleft, but its a bunch of rules on static linking, what constitutes a "work", major contribution, and isolation.
Everything AGPLv3+ is no problem though.

It last changed here https://github.com/kimai/kimai/blame/95e06746bd6eaa65db7b4576257447240e26e70b/translations/actions.en.xlf#L85
This is the string on Weblate https://hosted.weblate.org/translate/kimai/actions/en/?checksum=8927d0a2b88a8641
Maybe a collision with an identical "trans-unit id" other than `aP9j_4L` created for a translation or source file?

I think if you did the consistency plugin it shares the same translation for many keys.
Maybe marking it as "needs work" with the source as translation is how existing discrepancies are handled?

I can only see https://hosted.weblate.org/changes/?project=kimai&lang=&action=61&action=60&action=42&action=41&action=54&action=62&user=&start_date=&end_date= and not the actual config (since I am not an admin).
Don't know what "prefill" is. If you add "kingu" I can check all of them and make sure they aren't set up to do further damage (which I managed to do once).

**Comment by kevinpapst** [comment] 2023-01-27 11:39
Found the problem. That is a rather edgy weblate bug: if two git repositories are used in one project and both have keys with the same name (like `download` or `contact` in this case) and one repository resets the string for a currently missing language to the base language, then this key in reset in all components (instead of only resetting the key in the component and language where the consistency or prefill plugin is configured).

I did a manual merge yesterday, fixed these keys and also changed some of which you marked/changed before. 

Closing here, I think the licenses are good now 😄 thanks for bringing that discussion up!

**Closed as completed by kevinpapst** 2023-01-27 11:39 UTC
Labels: translation
