### ISSUE TITLE
language settings need to be user specific

### ISSUE THREAD

**Issue by actXc** [kimai/kimai#536] opened 2016-01-02 14:40 UTC
kimai has the build in option to use different languages.
But a user can not benefit from it.

Because the format for time and money is also language dependent, this is a big change in kimai.

Step1) 
implement a user field for language selection, 
when rendering the page, the users language is selected.

Step2) 
implement advanved user-settings including time and money settings per user.

**Comment by kevinpapst** [comment] 2016-03-02 21:13
Hi @actXc,

1) There is a user specific language setting, did you not see it in preferences or is that not what you had in mind? This setting will overwrite the global language setting.

2) Time could be user specific in its formatting.

But money is a major problem, as we do not store the currency, but only the amount.
Can you give me a use case where you would want to use several currencies? Think about invoices and everything related to calculating sums or budgets ... how should that be implemented with mixed currencies?
From my POV, Kimai is not the correct software for handling (large amounts of) mixed money data.

**Comment by kevinpapst** [comment] 2017-12-16 13:05
Closing, as there was no feedback. This is partially a duplicate of #1064

**Closed by kevinpapst** 2017-12-16 13:05 UTC
Labels: Feature Request
