### ISSUE TITLE
LDAP problem with login (depricated)

### ISSUE THREAD

**Issue by DunklerPhoenix** [kimai/kimai#3988] opened 2023-04-25 17:39 UTC
### Describe the issue

Heho
LDAP seems to be broken in v2 (or I am to stupid :P)
I use OpenLDAP

Here is my local.yaml
```

kimai:
    ldap:
        activate: true
        connection:
            host: ldap
            useSsl: false
            port: 543
            username: readonly
            password: readonly
            # auto generated fallback is the same, no need to set it explicit:
            #accountFilterFormat: (&(objectClass=posixAccount)(uid=%s))
        user:
            baseDn: ou=people, dc=myfancycompany, dc=ch
            filter: (&(objectClass=posixAccount))
            usernameAttribute: uid
            attributes:
                - { ldap_attr: uid, user_method: setUsername }
                - { ldap_attr: givenName, user_method: setAlias }
                - { ldap_attr: mail, user_method: setEmail }
        role:
            baseDn: ou=people, dc=myfancycompany, dc=ch
            filter: (&(objectClass=groupOfUniqueNames)(|(cn=zeit_administrator)(cn=zeit_systemadministrator)(cn=zeit_teamleiter)))
            userDnAttribute: uniqueMember
            usernameAttribute: uid
            groups:
                - { ldap_value: zeit_teamleiter, role: ROLE_TEAMLEAD }
                - { ldap_value: zeit_administrator, role: ROLE_ADMIN }
                - { ldap_value: zeit_systemadministrator, role: ROLE_SUPER_ADMIN }
```

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.14

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Logfile

```

[2023-04-25T17:31:22.638174+00:00] request.CRITICAL: Uncaught PHP Exception App\Ldap\LdapDriverException: "An error occurred with the search operation." at /opt/kimai/src/Ldap/LdapDriver.php line 72 {"exception":"[object] (App\\Ldap\\LdapDriverException(code: 0): An error occurred with the search operation. at /opt/kimai/src/Ldap/LdapDriver.php:72)"} []
[2023-04-25T17:31:22.629134+00:00] app.ERROR: Laminas\Ldap\Exception\LdapException: Binding requires username in DN form in /opt/kimai/vendor/laminas/laminas-ldap/src/Ldap.php:971 Stack trace: #0 /opt/kimai/src/Ldap/LdapDriver.php(64): Laminas\Ldap\Ldap->bind() #1 /opt/kimai/src/Ldap/LdapManager.php(41): App\Ldap\LdapDriver->search('ou=people, dc=b...', '(&(&(objectClas...') #2 /opt/kimai/src/Ldap/LdapUserProvider.php(27): App\Ldap\LdapManager->findUserByUsername('MyFancyUsername') #3 /opt/kimai/vendor/symfony/security-core/User/ChainUserProvider.php(61): App\Ldap\LdapUserProvider->loadUserByIdentifier('MyFancyUsername') #4 /opt/kimai/src/Security/KimaiUserProvider.php(63): Symfony\Component\Security\Core\User\ChainUserProvider->loadUserByIdentifier('MyFancyUsername') #5 /opt/kimai/vendor/symfony/security-http/Authenticator/Passport/Badge/UserBadge.php(79): App\Security\KimaiUserProvider->loadUserByIdentifier('MyFancyUsername') #6 /opt/kimai/vendor/symfony/security-http/Authenticator/Passport/Passport.php(56): Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge->getUser() #7 /opt/kimai/vendor/symfony/security-http/EventListener/UserCheckerListener.php(42): Symfony\Component\Security\Http\Authenticator\Passport\Passport->getUser() #8 /opt/kimai/vendor/symfony/event-dispatcher/EventDispatcher.php(246): Symfony\Component\Security\Http\EventListener\UserCheckerListener->preCheckCredentials(Object(Symfony\Component\Security\Http\Event\CheckPassportEvent), 'Symfony\\Compone...', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #9 /opt/kimai/vendor/symfony/event-dispatcher/EventDispatcher.php(206): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}(Object(Symfony\Component\Security\Http\Event\CheckPassportEvent), 'Symfony\\Compone...', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #10 /opt/kimai/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'Symfony\\Compone...', Object(Symfony\Component\Security\Http\Event\CheckPassportEvent)) #11 /opt/kimai/vendor/symfony/security-http/Authentication/AuthenticatorManager.php(176): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\Security\Http\Event\CheckPassportEvent)) #12 /opt/kimai/vendor/symfony/security-http/Authentication/AuthenticatorManager.php(154): Symfony\Component\Security\Http\Authentication\AuthenticatorManager->executeAuthenticator(Object(Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticator), Object(Symfony\Component\HttpFoundation\Request)) #13 /opt/kimai/vendor/symfony/security-http/Authentication/AuthenticatorManager.php(136): Symfony\Component\Security\Http\Authentication\AuthenticatorManager->executeAuthenticators(Array, Object(Symfony\Component\HttpFoundation\Request)) #14 /opt/kimai/vendor/symfony/security-http/Firewall/AuthenticatorManagerListener.php(40): Symfony\Component\Security\Http\Authentication\AuthenticatorManager->authenticateRequest(Object(Symfony\Component\HttpFoundation\Request)) #15 /opt/kimai/vendor/symfony/security-http/Authenticator/Debug/TraceableAuthenticatorManagerListener.php(65): Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener->authenticate(Object(Symfony\Component\HttpKernel\Event\RequestEvent)) #16 /opt/kimai/vendor/symfony/security-bundle/Debug/WrappedLazyListener.php(46): Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticatorManagerListener->authenticate(Object(Symfony\Component\HttpKernel\Event\RequestEvent)) #17 /opt/kimai/vendor/symfony/security-http/Firewall/AbstractListener.php(26): Symfony\Bundle\SecurityBundle\Debug\WrappedLazyListener->authenticate(Object(Symfony\Component\HttpKernel\Event\RequestEvent)) #18 /opt/kimai/vendor/symfony/security-bundle/Debug/TraceableFirewallListener.php(73): Symfony\Component\Security\Http\Firewall\AbstractListener->__invoke(Object(Symfony\Component\HttpKernel\Event\RequestEvent)) #19 /opt/kimai/vendor/symfony/security-http/Firewall.php(92): Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener->callListeners(Object(Symfony\Component\HttpKernel\Event\RequestEvent), Object(Generator)) #20 /opt/kimai/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(116): Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)) #21 /opt/kimai/vendor/symfony/event-dispatcher/EventDispatcher.php(206): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)) #22 /opt/kimai/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\RequestEvent)) #23 /opt/kimai/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(127): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request') #24 /opt/kimai/vendor/symfony/http-kernel/HttpKernel.php(139): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request') #25 /opt/kimai/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #26 /opt/kimai/vendor/symfony/http-kernel/Kernel.php(184): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #27 /opt/kimai/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #28 /opt/kimai/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run() #29 /opt/kimai/public/index.php(5): require_once('/opt/kimai/vend...') #30 {main} {"exception":"[object] (Laminas\\Ldap\\Exception\\LdapException(code: 0): Binding requires username in DN form at /opt/kimai/vendor/laminas/laminas-ldap/src/Ldap.php:971)"} []
[2023-04-25T17:31:22.625367+00:00] deprecation.INFO: User Deprecated: Method "ArrayAccess::offsetUnset()" might add "void" as a native return type declaration in the future. Do the same in implementation "Laminas\Ldap\Dn" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"ArrayAccess::offsetUnset()\" might add \"void\" as a native return type declaration in the future. Do the same in implementation \"Laminas\\Ldap\\Dn\" now to avoid errors or add an explicit @return annotation to suppress this message. at /opt/kimai/vendor/symfony/error-handler/DebugClassLoader.php:337)"} []
[2023-04-25T17:31:22.624880+00:00] deprecation.INFO: User Deprecated: Method "ArrayAccess::offsetSet()" might add "void" as a native return type declaration in the future. Do the same in implementation "Laminas\Ldap\Dn" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"ArrayAccess::offsetSet()\" might add \"void\" as a native return type declaration in the future. Do the same in implementation \"Laminas\\Ldap\\Dn\" now to avoid errors or add an explicit @return annotation to suppress this message. at /opt/kimai/vendor/symfony/error-handler/DebugClassLoader.php:337)"} []
[2023-04-25T17:31:22.624489+00:00] deprecation.INFO: User Deprecated: Method "ArrayAccess::offsetGet()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Laminas\Ldap\Dn" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"ArrayAccess::offsetGet()\" might add \"mixed\" as a native return type declaration in the future. Do the same in implementation \"Laminas\\Ldap\\Dn\" now to avoid errors or add an explicit @return annotation to suppress this message. at /opt/kimai/vendor/symfony/error-handler/DebugClassLoader.php:337)"} []
[2023-04-25T17:31:22.623618+00:00] deprecation.INFO: User Deprecated: Method "ArrayAccess::offsetExists()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Laminas\Ldap\Dn" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"ArrayAccess::offsetExists()\" might add \"bool\" as a native return type declaration in the future. Do the same in implementation \"Laminas\\Ldap\\Dn\" now to avoid errors or add an explicit @return annotation to suppress this message. at /opt/kimai/vendor/symfony/error-handler/DebugClassLoader.php:337)"} []
[2023-04-25T17:31:22.616534+00:00] app.ERROR: ldap_search(ou=people, dc=myfancycompany, dc=ch, (&(&(objectClass=posixAccount))(uid=MyFancyUsername)), array["+","*"]) {"action":"ldap_search","base_dn":"ou=people, dc=myfancycompany, dc=ch","filter":"(&(&(objectClass=posixAccount))(uid=MyFancyUsername))","attributes":["+","*"]} []

```

### Stacktrace

```
App\Ldap\LdapDriverException:
An error occurred with the search operation.

  at src/Ldap/LdapDriver.php:72
  at App\Ldap\LdapDriver->search('ou=people, dc=myfancycompany, dc=ch', '(&(&(objectClass=posixAccount))(uid=MyFancyUsername))')
     (src/Ldap/LdapManager.php:41)
  at App\Ldap\LdapManager->findUserByUsername('MyFancyUsername')
     (src/Ldap/LdapUserProvider.php:27)
  at App\Ldap\LdapUserProvider->loadUserByIdentifier('MyFancyUsername')
     (vendor/symfony/security-core/User/ChainUserProvider.php:61)
  at Symfony\Component\Security\Core\User\ChainUserProvider->loadUserByIdentifier('MyFancyUsername')
     (src/Security/KimaiUserProvider.php:63)
  at App\Security\KimaiUserProvider->loadUserByIdentifier('MyFancyUsername')
     (vendor/symfony/security-http/Authenticator/Passport/Badge/UserBadge.php:79)
  at Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge->getUser()
     (vendor/symfony/security-http/Authenticator/Passport/Passport.php:56)
  at Symfony\Component\Security\Http\Authenticator\Passport\Passport->getUser()
     (vendor/symfony/security-http/EventListener/UserCheckerListener.php:42)
  at Symfony\Component\Security\Http\EventListener\UserCheckerListener->preCheckCredentials(object(CheckPassportEvent), 'Symfony\\Component\\Security\\Http\\Event\\CheckPassportEvent', object(EventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:246)
  at Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}(object(CheckPassportEvent), 'Symfony\\Component\\Security\\Http\\Event\\CheckPassportEvent', object(EventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:206)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure)), 'Symfony\\Component\\Security\\Http\\Event\\CheckPassportEvent', object(CheckPassportEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(CheckPassportEvent))
     (vendor/symfony/security-http/Authentication/AuthenticatorManager.php:176)
  at Symfony\Component\Security\Http\Authentication\AuthenticatorManager->executeAuthenticator(object(TraceableAuthenticator), object(Request))
     (vendor/symfony/security-http/Authentication/AuthenticatorManager.php:154)
  at Symfony\Component\Security\Http\Authentication\AuthenticatorManager->executeAuthenticators(array(object(TraceableAuthenticator), object(TraceableAuthenticator)), object(Request))
     (vendor/symfony/security-http/Authentication/AuthenticatorManager.php:136)
  at Symfony\Component\Security\Http\Authentication\AuthenticatorManager->authenticateRequest(object(Request))
     (vendor/symfony/security-http/Firewall/AuthenticatorManagerListener.php:40)
  at Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener->authenticate(object(RequestEvent))
     (vendor/symfony/security-http/Authenticator/Debug/TraceableAuthenticatorManagerListener.php:65)
  at Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticatorManagerListener->authenticate(object(RequestEvent))
     (vendor/symfony/security-bundle/Debug/WrappedLazyListener.php:46)
  at Symfony\Bundle\SecurityBundle\Debug\WrappedLazyListener->authenticate(object(RequestEvent))
     (vendor/symfony/security-http/Firewall/AbstractListener.php:26)
  at Symfony\Component\Security\Http\Firewall\AbstractListener->__invoke(object(RequestEvent))
     (vendor/symfony/security-bundle/Debug/TraceableFirewallListener.php:73)
  at Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener->callListeners(object(RequestEvent), object(Generator))
     (vendor/symfony/security-http/Firewall.php:92)
  at Symfony\Component\Security\Http\Firewall->onKernelRequest(object(RequestEvent), 'kernel.request', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:116)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(RequestEvent), 'kernel.request', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:206)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(RequestEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(RequestEvent), 'kernel.request')
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:127)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(RequestEvent), 'kernel.request')
     (vendor/symfony/http-kernel/HttpKernel.php:139)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:184)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/opt/kimai/vendor/autoload_runtime.php')
     (public/index.php:5)        
```

**Comment by kevinpapst** [comment] 2023-04-25 19:35
> Binding requires username in DN form  

Your username: readonly <= that is not DN form, is it?

Either try to set `bindRequiresDn: false` or configure full username including DN

**Comment by kevinpapst** [comment] 2023-04-25 19:36
BTW: that is not a bug, so I am closing.

**Closed as completed by kevinpapst** 2023-04-25 19:36 UTC
Labels: support
