### ISSUE TITLE
Cannot edit time tracking entry

### ISSUE THREAD

**Issue by SMundt** [kimai/kimai#483] opened 2015-05-05 14:56 UTC
Hello,

I can't edit an time tracking entry.
If I click on "OK" in the dialog, nothing happens.

Which information do you need from me for help?

**Comment by kevinpapst** [comment] 2015-05-05 16:52
Check your Javascript console if there is any error.
Also: what did you do before? Upgrade? Was it ever working?
Are you creating or updating an entry?

2015-05-05 16:56 GMT+02:00 SMundt <notifications@github.com>:

**Comment by SMundt** [comment] 2015-05-05 22:05
In the JavaScript console I only found this:

getAttributeNode() should not be used anymore. Please use getAttribute() instead. jquery-1.9.1.min.js:3:0
getPreventDefault() should not be used anymore. Please use defaultPrevented instead. jquery-1.9.1.min.js:2:0


It is a fresh installation of today of the version here on github.
I've found out that I cannot add an entry or edit an entry.
Everytime when I click on "OK" in the dialog than nothing happens.
In the debug log I found the following line every time I click on "OK":

[05.05.2015 23:59:02] Uncaught exception: Could not determine temp directory, please specify a cache_dir manually

**Comment by simonschaufi** [comment] 2015-05-06 01:51
> [05.05.2015 23:59:02] Uncaught exception: Could not determine temp directory, please specify a cache_dir manually

I know a solution to this. A bit ugly but this is it:

in file:
```
core/libraries/Zend/Cache/Backend/File.php
```
set:
```
'cache_dir' => '/absolute/path/to/kimai/core/temporary', 
```
then it should work.

**Comment by SMundt** [comment] 2015-05-06 08:02
I've changed the cache_dir as described to a folder on my webspace.
Now the error message doesn't appear in the debug log:

[06.05.2015 09:56:19] Global role 1 gave true for ki_timesheets-editRates.
[06.05.2015 09:56:19] Global role 1 gave true for ki_timesheets-ownEntry-edit.
[06.05.2015 09:56:19] KSPI axAction (admin): add_edit_timeSheetEntry
[06.05.2015 09:56:19] Global role 1 gave true for ki_timesheets-editRates.
[06.05.2015 09:56:19] Global role 1 gave true for ki_timesheets-ownEntry-edit.
[06.05.2015 09:56:19] KSPI axAction (admin): add_edit_timeSheetEntry
[06.05.2015 09:56:19] Global role 1 gave true for ki_timesheets-editRates.
[06.05.2015 09:56:19] Global role 1 gave true for ki_timesheets-ownEntry-edit. 

But the OK button still doesn't work :(

**Comment by SMundt** [comment] 2015-05-11 14:10
Hello,

now I reinstalled Kimai but still cannot add or edit a timesheet entry.
Any ideas?

**Comment by SMundt** [comment] 2015-05-11 14:34
I've installed firebug and get the following error If I click on ok:

![1](https://cloud.githubusercontent.com/assets/12255583/7567157/9225cf76-f7fb-11e4-99ee-9513a27e4db4.PNG)

![2](https://cloud.githubusercontent.com/assets/12255583/7567164/979ec0de-f7fb-11e4-8f49-bd49180aac7c.PNG)

I hope this helps???

**Comment by simonschaufi** [comment] 2015-05-11 16:29
do you have access to the php server logs? that would be really helpful in the case of an internal server error

**Comment by SMundt** [comment] 2015-05-11 16:54
Hello,

I've created the PHP error log via .htaccess file.
If I click on OK in the dialog I get the following log entry:

[11-May-2015 18:50:24 Europe/Berlin] PHP Parse error:  syntax error, unexpected ''cache_dir'' (T_CONSTANT_ENCAPSED_STRING), expecting variable (T_VARIABLE) in /www/htdocs/myserverdir/kimai/libraries/Zend/Cache/Backend/File.php on line 92

In libraries/Zend/Cache/Backend/File.php I set the cache dir in line 91:
'cache_dir' => '/www/htdocs/myserverdir/kimai/temp'),

the temp dir has chmod 777 rights.

Do you need more information?

**Comment by simonschaufi** [comment] 2015-05-11 16:58
if you set the cache_dir in line 91, what about line 92?

**Comment by SMundt** [comment] 2015-05-11 16:58
Oh my god, I've found my mistake...
The bracket behind ..../temp' was too much :(

Sorry and a special thanks to you for your help!!!

**Comment by simonschaufi** [comment] 2015-05-11 16:59
good, i hope the problem is solved now ;)

**Comment by SMundt** [comment] 2015-05-11 17:00
Yes, now it works as it should! 
Thank you very much!

**Comment by simonschaufi** [comment] 2015-05-11 17:00
ok, then please close this issue. thanx

**Closed** 2015-05-11 17:00 UTC

**Comment by kevinpapst** [comment] 2016-07-07 08:33
The problem is finally solved in Kimai: https://github.com/kimai/kimai/pull/731
