### ISSUE TITLE
v2 seems sluggish

### ISSUE THREAD

**Issue by winternet-studio** [kimai/kimai#4463] opened 2023-11-29 11:11 UTC
### Describe the problem

The transitions/animations used on modals in v2 make the system seems sluggish - takes a second or so when clicking on a timesheet before the modal shows up or disappears! A system needs to be snappy, rather than fancy looking.

### Describe the solution you'd like

Speed up the transitions a lot, or leave them out entirely.

**Comment by kevinpapst** [comment] 2023-11-29 11:39
Consider your hardware or browser settings as well.

The v2 version is out since a year and the only person that had an issue was someone how used a remote RDP session to a Windows machine. 

Check if that helps: https://github.com/kimai/kimai/discussions/4415

**Comment by kevinpapst** [comment] 2024-01-21 01:07
Closing as duplicate of https://github.com/kimai/kimai/issues/4486

**Closed as completed by kevinpapst** 2024-01-21 01:07 UTC
Labels: feature request
