### ISSUE TITLE
Date Format problems

### ISSUE THREAD

**Issue by DaLooK** [kimai/kimai#1066] opened 2017-11-03 18:17 UTC
#### Expected behaviour
Select the date in format "m.d.Y"

#### Actual behaviour
When selecting a date via the widget, date changes.

#### Steps to reproduce
Set date format to "m.d.Y" (or similar)
The point is that is different from "d.m.Y".
Go to "Timesheet"
Add new entry.
Select date "October 30, 2017"
Date goes to "10.7.2019" (Which is October 7, 2017)

#### Reason
The "_ts_getDateFromStrings_" function inside "_extensions/ki_timesheets/js/ts_func.js_" always expect the "d.m.Y" date format.

#### Reproducable on demo.kimai.org?
YES

#### Kimai version 
1.1.0.1389 stable

**Comment by simonschaufi** [comment] 2017-11-08 00:45
I think this is a duplicate of #139, or?

**Closed by simonschaufi** 2017-11-08 00:45 UTC
