### ISSUE TITLE
adding users and they can not login

### ISSUE THREAD

**Issue by jasonrx8** [kimai/kimai#506] opened 2015-07-08 04:05 UTC
hi 

installed the system on my server today , ive setup a user and given them a password , when you try and login you put details in and press the button and it is like it is on a loop it comes back to the start again login and it does the same thing again 

there is no error or anything , if i put wrong password it gives me the big red box with password error so it knows the account is there 

admin account works fine just any other account doesnt work

thanks in advance

**Comment by simonschaufi** [comment] 2015-07-08 11:03
Do you use the latest release (from the website) or the version from github?

**Comment by ServiusHack** [comment] 2015-07-09 17:35
The issue is most likely that users were locked by default after they were created. You need to click on the little lock symbol to unlock the user. He is then able to login. This was fixed with #145.

**Closed by ServiusHack** 2015-07-09 17:35 UTC
