### ISSUE TITLE
MISSING FEATURE: Edit while tracking

### ISSUE THREAD

**Issue by lippoliv** [kimai/kimai#52] opened 2012-10-22 09:19 UTC
MISSING FEATURE: While tracking a Task in Kimai 1366 i was able to modify Comment and Start-Time (sometimes i forgot to start tracking, than i start tracking and modify the start-time for some minutes), why is it gone?

**Comment by jniggemann** [comment] 2016-01-15 15:05
+1, please reimplement this

**Comment by simonschaufi** [comment] 2016-01-18 18:44
can this issue be closed with the PR from @claudegel which is already merged?

**Comment by jniggemann** [comment] 2016-01-18 20:05
I guess that depends on how you use the issue tracker :-)
Either you keep this issue open until a version is released that contains the fix OR you close it, as the issue is fixed in the current trunk.

**Comment by simonschaufi** [comment] 2016-01-19 20:21
If the feature is the one requested which is already merged again, I'll close this issue now. if it isn't, please comment again and tell me what you are expecting.

**Closed by simonschaufi** 2016-01-19 20:21 UTC
Labels: Feature Request
