### ISSUE TITLE
Quick comment edit (Speech Balloon) missing after upgrading from version 0.9.2.1306 to  0.9.3.1384

### ISSUE THREAD

**Issue by frederickjh** [kimai/kimai#719] opened 2016-06-21 14:41 UTC
#### Expected behaviour
Clicking on a speech balloon icon by time counter allows comments to be quickly edited.
#### Actual behaviour
The speech balloon icon by time counter is gone.
#### Steps to reproduce the behaviour
Install version 0.9.3.1384 of Kimai
#### Kimai version
0.9.3.1384
#### Relevant log entries from Kimais Debug tab
N/A

Hi!
I used this feature a lot in the previous version of Kimai. I know it is still possible to edit the comment for the current event being timed: pencil icon > Advanced (Tab) then edit the comment. Just not as quick as the speech balloon icon was. Please consider bringing it back.
Thanks!
Frederick

**Comment by frederickjh** [comment] 2016-06-21 14:47
Sorry the documentation calls what I called a **speech ballon** a **comments bubble**.  See the sub-section **Editing your time** of the [Timesheet section of the Documents](http://www.kimai.org/documentation/manual/timesheet.html).

**Comment by simonschaufi** [comment] 2016-06-21 15:54
In the user settings there is a new setting for that. This whole thing has been merged with #436

**Closed by simonschaufi** 2016-06-21 15:54 UTC

**Comment by frederickjh** [comment] 2016-06-21 21:49
Hi @simonschaufi !
I dug through #436, but I am not certain that it is in there. I also went through the preferences and could not find it there, maybe I am just missing it. Which tab is it under and what is it called?

This was definitely in v0.9.2.1306. I just moved that version to new hosting and then upgraded to 0.9.3.1384 and found it missing. I am attaching a screenshot showing the **comments bubble** next to the counter.
Thanks for taking another look at this!
Frederick

![kimai_comments_bubble_in_version_0 9 2 1306](https://cloud.githubusercontent.com/assets/864159/16247590/b92fd0b2-380a-11e6-91ca-bc362ee526a6.png)

**Comment by simonschaufi** [comment] 2016-06-21 23:17
It's in the list tab and called show quick note button. Maybe you need to checkout latest master to see this feature, i think it's not in the latest release.

**Comment by frederickjh** [comment] 2016-06-22 07:17
You are correct it is not in the current release. I just checked the demo site and there it is present in the place you mentioned. How often do you issue releases? I see that the last one was in October. The commit of the pull request that implemented this feature was in December. Just curious if you have any plans for a release soon.

**Comment by simonschaufi** [comment] 2016-06-22 07:38
Ok. I have really no idea when the bubble was removed.
Well, we don't commit ourselves onto a date, we just think what should be in a release. The faster it gets done, the faster a new release will come out. You can always track the current status with milestone:1.0

**Comment by frederickjh** [comment] 2016-06-22 13:33
Now I find that if I edit a currently running event it stops the event.  I have had enough. I have gone back to my previous version 0.9.2. I am too busy to have to monkey around with this software.

**Comment by kevinpapst** [comment] 2016-06-22 14:01
Wow... taking a free software for granted and then bullying around when it doesn't work as expected. Thanks for your encouragment, thats the spirit of OpenSource! 
What about filling a a bug report for the development version, so we can improve it?

**Comment by simonschaufi** [comment] 2016-06-22 14:11
@frederickjh I tried to reproduce your issue about editing an event and then it stops but I couldn't reproduce it. Can you please confirm it doesn't work on the demo website?

**Comment by frederickjh** [comment] 2016-06-22 15:49
@kevinpapst sorry, not taking in for granted. Just frustrated with one of the downsides to open source. Documentation about changes that are lacking. Some do it well others write "Lots of bug fixes and improvements."  

My experience with Kimai has been anything but easy when it comes to installing and moving. I am not sure why that is. I work with other open source web apps (CMSs and Mailing list, etc.) and have fewer issues with installing and moves with them than with Kimai.

@simonschaufi I have tested the issue I meantioned on the latest dev on the demo site and it does not happen. May be a regression in the release that got fixed later. I wish there was a way to see what commits end up in what release and which have not yet been released here on github.

Thanks for your work on Kimai! In day-to-day use I have no problems and it work well for what it does.
Frederick

**Comment by frederickjh** [comment] 2016-06-22 15:53
@simonschaufi, Sorry I take that back I just tried a test or two more test on the demo site and found what triggers the timer to stop.

If you edit the currently running event and then click the **now** button to fill in the current date and time into the end fields then click **OK**, the timing for the event stops.

**Comment by simonschaufi** [comment] 2016-06-22 15:56
> If you edit the currently running event and then click the now button to fill in the current date and time into the end fields then click OK, the timing for the event stops.

Jup, thats on purpose. Why should the event continue to run if you "stop" it by filling in end times? Doesn't make sense.

**Comment by frederickjh** [comment] 2016-06-22 15:56
Debug for the session looks like this:
<pre>[22.06.2016 17:53:09] KSPI axAction (admin): shoutbox 
[22.06.2016 17:53:02] KSPI axAction (admin): reload_timeSheet 
[22.06.2016 17:53:02] timeEntry_edit: 47 
[22.06.2016 17:53:02] KSPI axAction (admin): add_edit_timeSheetEntry 
[22.06.2016 17:52:56] KSPI axAction (admin): reload_activities_options 
[22.06.2016 17:52:56] KSPI axAction (admin): add_edit_timeSheetEntry 
[22.06.2016 17:52:54] KSPI axAction (admin): reload_timeSheet 
[22.06.2016 17:52:54] get_best_fitting_rate - using default rate 0.00
[22.06.2016 17:52:54] KSPI axAction (admin): startRecord 
</pre>

**Comment by simonschaufi** [comment] 2016-06-22 15:58
> I wish there was a way to see what commits end up in what release and which have not yet been released here on github.

I try to make that very clear with assigning the issues to mile stones. Anything in this milestone should be in the latest release. https://github.com/kimai/kimai/issues?q=milestone%3A0.9.3

**Comment by frederickjh** [comment] 2016-06-22 16:06
I guess I have worked with a modified Kimai for so long I did not think of that.  I add a modification I found in the Kimai forum in this [topic](http://forum.kimai.org/index.php?topic=1677.0).

It allowed you to edit the currently running event but you could not save it unless you filled in the end date and time, usually with the now button. The time would continue to run and  the end time would then be updated with time when the stop button was clicked.

I guess after having to do things wrong for so long it never occurred to me that it was the correct procedure. 

However it is not clear that this will happen from the interface. Maybe the **now** should be on a stop button like in the main window to make this clearer. Just my two cents.

**Comment by simonschaufi** [comment] 2016-06-22 17:22
Aha, that makes sense ;) Of course we cannot provide support for self patched kimai installations ;)

Feel free to make a pull request to change things.
