### ISSUE TITLE
issues with Italian language

### ISSUE THREAD

**Issue by inside54** [kimai/kimai#1234] opened 2019-11-11 15:27 UTC
when I set the Italian language I lose the graphic interface on the dashboard, the other pages are displayed correctly

![Screenshot+2019-11-11+04 21 45](https://user-images.githubusercontent.com/57178517/68598880-e5cdc380-049f-11ea-881b-1e00250cdd1f.jpg)

**Comment by kevinpapst** [comment] 2019-11-11 15:58
Wow, okay. Missing translations shouldn't break the app obviously.

Thanks for the report, I'll check that.

**Comment by inside54** [comment] 2019-11-11 16:39
Here the IT translation files I have in htdocs\kimai\translations 
hope they re useful
![Screenshot+2019-11-11+05 35 11](https://user-images.githubusercontent.com/57178517/68604112-0a2e9d80-04aa-11ea-89a4-e67142d29ad9.png)

**Comment by kevinpapst** [comment] 2019-11-11 16:42
Does that ONLY happen with the "it" translations?
I cannot reproduce the error, this page works correctly: https://demo.kimai.org/it/dashboard/

Did you change a file?
Is there anything in the Kimai log that looks suspicious? Check the "Doctor" page => Logs. Or inside Kimai var/logs/prod.log

**Comment by kevinpapst** [comment] 2019-12-01 21:00
No feedback, closing

**Closed as completed by kevinpapst** 2019-12-01 21:00 UTC
Labels: waiting for feedback
