### ISSUE TITLE
PHP error whilst attempting to install

### ISSUE THREAD

**Issue by rolandheymanns** [kimai/kimai#1086] opened 2018-01-09 20:54 UTC
#### Expected behaviour
Install

#### Actual behaviour
Hangs at "System Requirements"

#### Steps to reproduce
"Check requirements now"

#### Reproducable on demo.kimai.org? [yes|no]
Invalid login credentials, using 'admin' and 'changeme'

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.1.0.1389

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
[Wed Jan 10 09:47:49.909026 2018] [proxy_fcgi:error] [pid 10839] [client 127.0.0.1:56174] AH01071: Got error 'PHP message: PHP Notice:  A non well formed numeric value encountered in /srv/www/lib/php/time-tracking/kimai/installer/processor.php on line 38\nPHP message: PHP Stack trace:\nPHP message: PHP   1. {main}() /srv/www/lib/php/time-tracking/kimai/installer/processor.php:0\nPHP message: PHP   2. return_bytes() /srv/www/lib/php/time-tracking/kimai/installer/processor.php:97\n', referer: http://localhost/lib/php/time-tracking/kimai/installer/index.php

**Comment by kevinpapst** [comment] 2018-01-09 21:47
What PHP version are you running?

**Comment by simonschaufi** [comment] 2018-01-12 09:53
Duplicate of #1001 and #930.

**Closed by simonschaufi** 2018-01-12 09:53 UTC
