### ISSUE TITLE
How to apply same activities to multiple projects?

### ISSUE THREAD

**Issue by srdco** [kimai/kimai#347] opened 2018-10-07 00:57 UTC
**Describe the bug**
How can I add the same activity to multiple projects?

**To Reproduce**
1. Add a project. 
2. Add activities. 
3. Add another project. 
4. Try to add the same activities to another project.

**Expected behavior**
Be able to assign the same activity to multiple projects.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser Firefox
 - Version 61

**Additional context**
It seems like under Kimai v1, it *seems* like I could re-use activities, and apply a given activity to multiple projects. This works well for patent prosecution, where I have standard activities (research, office action response, claim drafting, etc), and need to apply them to different projects (Application X, Application Y, etc) with different clients.
I can't seem to see how to do that in Kimai v2. Am I missing something? Remembering wrong? Thanks!

**Comment by kevinpapst** [comment] 2018-10-07 10:43
No, you are right. That is not (yet) implemented in Kimai 2. Already n work though. 
I close this ticket as it is a duplicate of #200.
Follow PR #259 for status updates.

**Closed as completed by kevinpapst** 2018-10-07 10:43 UTC
Labels: duplicate

**Comment by kevinpapst** [comment] 2018-11-06 00:12
Just wanted to post an update:
Work on global activities is in its last steps, now you can either assign an activity to one project or you can leave the project empty - in this case the activity can be used in every project.
If you want to help and test it, you can use the PR #259
