### ISSUE TITLE
2.0: Timer does not update, Search filter is marked as active, time-format is bound to locale (24 vs 12 hour)

### ISSUE THREAD

**Issue by kpspu** [kimai/kimai#3857] opened 2023-02-19 20:39 UTC
### Describe the issue

Hi! Thank you very much for updating the design on the web client.
There are some small issues with the change:

1. There is no possibility to choose 24H time format if your timezone isn't in 24H list. For example, I live in Belgrade and can't use 24H time format instead of 12H time format.

    SOLUTION: Change language in User - Preferences on something with 24H time format. For example, English (Slovenia).

2. After recording the first time item there are "1" icon in filters, but I do not choose any filters. If I open filters, there weren't be any.

3. The button for time counter doesn't change without page refreshing. So counter isn't showing time counting now - it's freezed.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.1

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

Unknown

### Logfile

Couldn't find the logfile menu.
I am usin the last Chromium 110.0.5481.77 (Official Build) (64-bit) on Arch Linux. Everything is updated.

### Screenshots

![image](https://user-images.githubusercontent.com/32261191/219973863-d6bc7a22-1516-458f-b359-4593df17c598.png)

**Comment by kevinpapst** [comment] 2023-02-19 21:08
Thanks for your feedback!

1. The timezone is not connected to the 12h vs 24h setting. All format settings are pulled from the locale AKA "user language". Switch to any language or an english variant that does not use 12h => like `English (Slovenia)`.
2. Some filter has been set, probably date-range? Click the red `X` icon and compare filters before and after. The (1) should be gone after clicking the X.
3. Works for me. Please clear your browser cache and test another browser and/or private mode, to make sure that this is not some browser plugin.

I will add a help message to the user settings `language` to explain that the language is reponsible for the date/time/money formats as well.

**Comment by kpspu** [comment] 2023-02-20 08:52
> 3\. Works for me. Please clear your browser cache and test another browser and/or private mode, to make sure that this is not some browser plugin.

I have done it, thanks for the suggestion. Unfortunatelly issue wasn't fixed.
You see, on the screenshot - the page header itself knows it was 1:49, but inside the page it is 1:48 (the time I cleared all the page with all cashe).

![image](https://user-images.githubusercontent.com/32261191/220057615-6c2a8b94-512b-44d5-bd3b-647b6d88e158.png)

Sometimes I saw even more confusing picture - all three times were different.

**Comment by kpspu** [comment] 2023-02-20 08:56
> 1. The timezone is not connected to the 12h vs 24h setting. All format settings are pulled from the locale AKA "user language". Switch to any language or an english variant that does not use 12h => like `English (Slovenia)`.

English (Slovenia) hasn't changed 12H on 24H... Are you sure it is working trhough you language and not time locale?

UPD: Yes, changing the language is changing the time local. But you need to change it not in the Settings - Users, but in User - Preferences.

**Comment by kpspu** [comment] 2023-02-20 08:57
> 2\. Some filter has been set, probably date-range? Click the red `X` icon and compare filters before and after. The (1) should be gone after clicking the X.

No, the isn't any. You can check the screenshot. The X button was the first I did, but the "1" sign will appear again after pressing Play button again.

![image](https://user-images.githubusercontent.com/32261191/220059152-527f1acb-aa06-4b8c-b5c9-27b429c0d603.png)

**Comment by kevinpapst** [comment] 2023-02-20 11:01
**Regarding the search:** 

Please try the following:
1. Remove all cookies for your Cloud Domain
2. Apply any search filter and click the "star/bookmark" icon to save that search as default. Now delete that bookmark again.

**Regarding the timer:**

I could now reproduce the issue. Will be fixed with the next update in the next days.

**Comment by kpspu** [comment] 2023-02-20 12:03
> Regarding the search:

Yes, it's fixed the "1" sign in filters. Thanks! It was fixed only after step 2, the only step 1 is not enough.

UPD: No, the "1" is back. Way to reproduce: Start the timer, Go to Dashboard, Return to My times.

**Comment by kevinpapst** [comment] 2023-02-20 12:36
Hm, that means it would be best to delete old search bookmarks during the update, to prevent that issue. Thanks 👍

**Comment by kpspu** [comment] 2023-02-20 13:10
> 

Just to clarify - I hadn't had any bookmarks before update. So we created one to delete them  :)

**Comment by kevinpapst** [comment] 2023-02-20 15:53
That's super weird. Maybe you created one by accident, without noticing?
Anyway: I'll try to reproduce that.

**Comment by stgpepper** [comment] 2023-02-20 16:08
I found a way to replicate #3 (timer). It seems that width of the screen affects wheter it shows real time (time) or what the page was loaded with. For me the brakepoint was between 991 pixels (less shows only unchanging time that the page was loaded with) and 992 (more shows it real time as it was before the update). Here are few examples from Firefox window with responsive design mode:

![kuva](https://user-images.githubusercontent.com/74211382/220154586-e761d915-867a-4125-9e92-60d59704e331.png)

![kuva](https://user-images.githubusercontent.com/74211382/220155031-84ddfae4-151f-433f-aa84-ec2130a75b7a.png)

Page was not refreshed between the screenshots. Only width was changed.

Edit: Now that I look them side by side it seems that it is the same brakepoint where left side menu reduces to hamburger menu automatically. 

Also thanks very much for the update! It is nice to see that the project is being taken good care.

**Comment by kevinpapst** [comment] 2023-02-20 16:12
And I thought it might be related to the user preference "Update browser title". Thank you for testing 👍

**Comment by kpspu** [comment] 2023-02-20 19:56
> No, the "1" is back. Way to reproduce: Start the timer, Go to Dashboard, Return to My times.

No, the "1" is back. Way to reproduce: Start the timer, Go to Dashboard, Return to My times.

**Comment by kevinpapst** [comment] 2023-02-20 23:34
Alright, I could fix the "duration / stop button / browser title" issue. Thanks for your input and help with testing!

I'll keep you posted about further progress.

**Closed as completed** 2023-02-21 18:21 UTC
Labels: bug

**Comment by kevinpapst** [comment] 2023-02-21 18:51
I updated the demo at https://demo-branch.kimai.org/  with the latest bugfixes.
Login with username `susan_super` and password `kitten`.

Would you give it a try and check if the errors are gone?

**Comment by stgpepper** [comment] 2023-02-22 06:35
On Item 3 I can confirm that timer is working for me as before even on smaller width window. Tested on Firefox version 110.0. The rest I didin't try.

**Comment by kevinpapst** [comment] 2023-02-22 15:50
Updates are currently running on the cloud. You should see the fixes within the next hour.

**Comment by kpspu** [comment] 2023-02-23 08:42
> Updates are currently running on the cloud. You should see the fixes within the next hour.

All issues have gone. Checked on the Cloud. Sorry, couldn't check the demo branch because of work.
Thank you very much!
