### ISSUE TITLE
Filter data for export time range dropdown always returns current month instead of the selected last month option

### ISSUE THREAD

**Issue by moritzgeisler** [kimai/kimai#4074] opened 2023-05-31 09:56 UTC
### Describe the issue

When using the "Last month" option from the "Time Range" dropdown menu the current month is selected instead of the last Month.

Example:
Date: 31/05/2023
When I click "Last month", the Time range field populates with "01/05/2023 - 31/05/2023" which is wrong as it is the current month.

I remember this worked before, therefore maybe related to that May has 31 days or latest updates?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.23

### How do you run Kimai?

Other (please mention below)

### Which PHP version are you using?

8.1

### Logfile

None

### Screenshots

![kimai_20230531_01](https://github.com/kimai/kimai/assets/133004748/46aee3c2-a448-4f52-b460-78d38e0ed62d)

**Comment by kevinpapst** [comment] 2023-05-31 09:59
Uh, a date related bug. How annoying...

I'll look into it today, because I assume it is not reproducible tomorrow.

**Comment by kevinpapst** [comment] 2023-05-31 17:24
Fixed in #4066

**Closed as completed** 2023-06-06 21:05 UTC
Labels: bug
