### ISSUE TITLE
Issue with form validation on POST api/timesheets

### ISSUE THREAD

**Issue by Pax-0** [kimai/kimai#5133] opened 2024-10-25 01:06 UTC
### Describe the issue

Hey, so am using the timesheets api, and passing headers for an account with `super-admin` perms and I can send GET and get 200 responses with the expected data from the documentation.

however if I try to send a POST to `<url>/api/timesheets` with the following body:

```
{
  "begin": "2024-10-24T21:42:00-0400",
  "end": "2024-10-24T21:45:00-0400",
  "project": 11,
  "activity": 1,
  "description": "testing",
  "user": 5
}
```

I get an error of:

```
{
    "code": 400,
    "message": "Validation Failed",
    "errors": {
        "errors": [
            "This form should not contain extra fields."
        ],
        "children": {
            "project": {},
            "activity": {},
            "description": {},
            "fixedRate": {},
            "hourlyRate": {},
            "user": {},
            "exported": {},
            "billable": {},
            "tags": {}
        }
    }
}
```
the issue is with the params of begin and end, they are listed as available on the documentation but from the error above it seems the api is somehow not allowing them specifically to be passed, 

shouldnt a 'super-admin' permission overide system settings to allow these params to be set for the newly created timesheet?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![image](https://github.com/user-attachments/assets/978ba5dd-d92d-4d7c-9813-dde2d09d839a)

**Comment by kevinpapst** [comment] 2024-10-25 06:21
Duplicate of #2241

**Closed as not planned by kevinpapst** 2024-10-25 06:21 UTC
Labels: bug
