### ISSUE TITLE
Strange behavior at random times

### ISSUE THREAD

**Issue by riaanj** [kimai/kimai#906] opened 2017-02-02 19:55 UTC
At random times we are not able to login to kimai.
when trying to log in it will just return to the login page with the following in the url index.php?a=logout

At random times when selecting a different project and activity, and it shows the activity selected at the top right of the screen. Kimai will record what you did previously when you press the start button.

At random times when trying to log in, it will log you in as someone else, who might be logged in at a different location

This behavior was also present in the previous version, it was then upgraded in the hope this will stop.

#### Reproducable on demo.kimai.org? [yes|no]
no

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
The version of Kimai is 1.1.0.1389 

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
[02.02.2017 19:14:01] login: hennie as user
[02.02.2017 19:16:35] KSPI axAction (hennie): reload_exp
[02.02.2017 19:16:36] KSPI axAction (hennie): reload
[02.02.2017 19:16:36] KSPI axAction (hennie): reload_timeSheet
[02.02.2017 19:16:40] KSPI axAction (hennie): reload_activities
[02.02.2017 19:16:40] KSPI axAction (hennie): saveBuzzerPreselection
[02.02.2017 19:23:42] KSPI axAction (hennie): startRecord
[02.02.2017 19:23:42] KSPI axAction (hennie): setTimeframe
[02.02.2017 19:23:42] get_best_fitting_rate - using default rate 0.00
[02.02.2017 19:23:42] KSPI axAction (hennie): reload_timeSheet
[02.02.2017 19:28:10] KSPI axAction (hennie): stopRecord
[02.02.2017 19:28:10] KSPI axAction (hennie): reload_timeSheet
[02.02.2017 19:31:11] KSPI axAction (hennie): add_edit_timeSheetEntry
[02.02.2017 19:31:11] KSPI axAction (hennie): reload_activities_options
[02.02.2017 19:31:14] KSPI axAction (hennie): bestFittingRates
[02.02.2017 19:31:14] get_best_fitting_rate - using default rate 0.00
[02.02.2017 19:31:15] KSPI axAction (hennie): budgets
[02.02.2017 19:31:16] KSPI axAction (hennie): add_edit_timeSheetEntry
[02.02.2017 19:31:16] timeEntry_edit: 2552
[02.02.2017 19:31:16] KSPI axAction (hennie): reload_timeSheet
[02.02.2017 19:31:19] KSPI axAction (hennie): add_edit_timeSheetEntry
[02.02.2017 19:31:20] KSPI axAction (hennie): reload_activities_options
[02.02.2017 19:31:31] KSPI axAction (hennie): add_edit_timeSheetEntry
[02.02.2017 19:31:31] timeEntry_edit: 2552
[02.02.2017 19:31:31] KSPI axAction (hennie): reload_timeSheet
[02.02.2017 19:58:06] KSPI axAction (hennie): reload_activities
[02.02.2017 19:58:07] KSPI axAction (hennie): saveBuzzerPreselection
[02.02.2017 19:58:09] KSPI axAction (hennie): saveBuzzerPreselection
[02.02.2017 19:58:35] Kicking user elene because of authentication key mismatch.
[02.02.2017 19:58:46] login: elene as user
[02.02.2017 19:58:55] login: elene as user
[02.02.2017 19:59:06] login: elene as user
[02.02.2017 19:59:16] login: elene as user
[02.02.2017 19:59:21] login: elene as user
[02.02.2017 19:59:28] login: elene as user
[02.02.2017 19:59:43] login: elene as user
[02.02.2017 19:59:49] login: elene@jbcon.co.za as user
[02.02.2017 20:02:35] KSPI axAction (hennie): startRecord
[02.02.2017 20:02:35] KSPI axAction (hennie): setTimeframe
[02.02.2017 20:02:35] get_best_fitting_rate - using default rate 0.00
[02.02.2017 20:02:35] KSPI axAction (hennie): reload_timeSheet
[02.02.2017 20:03:16] login: riaan as user
[02.02.2017 20:59:04] KSPI axAction (hennie): stopRecord
[02.02.2017 20:59:04] KSPI axAction (hennie): reload_timeSheet
[02.02.2017 21:10:16] login: elene as user
[02.02.2017 21:10:17] login: elene as user
[02.02.2017 21:10:38] KSPI axAction (elene): reload
[02.02.2017 21:10:38] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:10:38] KSPI axAction (elene): reload_exp
[02.02.2017 21:10:42] KSPI axAction (elene): reload_exp
[02.02.2017 21:10:42] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:10:42] KSPI axAction (elene): reload
[02.02.2017 21:10:45] KSPI axAction (elene): setTimeframe
[02.02.2017 21:10:45] KSPI axAction (elene): startRecord
[02.02.2017 21:10:45] get_best_fitting_rate - using default rate 0.00
[02.02.2017 21:10:45] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:10:47] KSPI axAction (elene): add_edit_timeSheetEntry
[02.02.2017 21:10:47] KSPI axAction (elene): reload_activities_options
[02.02.2017 21:11:04] KSPI axAction (elene): stopRecord
[02.02.2017 21:11:05] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:11:15] KSPI axAction (elene): add_edit_timeSheetEntry
[02.02.2017 21:11:15] timeEntry_edit: 2554
[02.02.2017 21:11:15] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:11:18] KSPI axAction (elene): add_edit_timeSheetEntry
[02.02.2017 21:11:18] KSPI axAction (elene): reload_activities_options
[02.02.2017 21:11:36] KSPI axAction (elene): add_edit_timeSheetEntry
[02.02.2017 21:11:36] timeEntry_edit: 2554
[02.02.2017 21:11:36] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:11:53] KSPI axAction (elene): reload_activities
[02.02.2017 21:11:53] KSPI axAction (elene): reload_activities
[02.02.2017 21:11:53] KSPI axAction (elene): saveBuzzerPreselection
[02.02.2017 21:11:55] KSPI axAction (elene): setTimeframe
[02.02.2017 21:11:55] KSPI axAction (elene): startRecord
[02.02.2017 21:11:55] get_best_fitting_rate - using default rate 0.00
[02.02.2017 21:11:55] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:11:57] KSPI axAction (elene): add_edit_timeSheetEntry
[02.02.2017 21:11:57] KSPI axAction (elene): reload_activities_options
[02.02.2017 21:12:27] KSPI axAction (elene): add_edit_timeSheetEntry
[02.02.2017 21:12:28] timeEntry_edit: 2555
[02.02.2017 21:12:28] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:12:29] KSPI axAction (elene): stopRecord
[02.02.2017 21:12:29] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:21:50] KSPI axAction (elene): reload
[02.02.2017 21:21:51] KSPI axAction (elene): reload_exp
[02.02.2017 21:21:51] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:21:52] KSPI axAction (elene): startRecord
[02.02.2017 21:21:52] get_best_fitting_rate - using default rate 0.00
[02.02.2017 21:21:52] KSPI axAction (elene): setTimeframe
[02.02.2017 21:21:52] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:22:42] KSPI axAction (elene): add_edit_timeSheetEntry
[02.02.2017 21:22:42] KSPI axAction (elene): reload_activities_options
[02.02.2017 21:43:01] KSPI axAction (elene): stopRecord
[02.02.2017 21:43:01] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:43:25] login: riaan as user
[02.02.2017 21:46:42] KSPI axAction (elene): add_edit_timeSheetEntry
[02.02.2017 21:46:43] timeEntry_edit: 2556
[02.02.2017 21:46:43] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:46:49] KSPI axAction (elene): saveBuzzerPreselection
[02.02.2017 21:46:49] KSPI axAction (elene): reload_activities
[02.02.2017 21:46:49] KSPI axAction (elene): reload_activities
[02.02.2017 21:46:51] KSPI axAction (elene): startRecord
[02.02.2017 21:46:51] get_best_fitting_rate - using default rate 0.00
[02.02.2017 21:46:51] KSPI axAction (elene): setTimeframe
[02.02.2017 21:46:51] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:46:55] KSPI axAction (elene): add_edit_timeSheetEntry
[02.02.2017 21:46:55] KSPI axAction (elene): reload_activities_options
[02.02.2017 21:47:34] KSPI axAction (elene): stopRecord
[02.02.2017 21:47:34] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:47:36] KSPI axAction (elene): add_edit_timeSheetEntry
[02.02.2017 21:47:37] timeEntry_edit: 2557
[02.02.2017 21:47:37] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:47:42] KSPI axAction (elene): add_edit_timeSheetEntry
[02.02.2017 21:47:42] KSPI axAction (elene): reload_activities_options
[02.02.2017 21:47:52] KSPI axAction (elene): add_edit_timeSheetEntry
[02.02.2017 21:47:52] timeEntry_edit: 2557
[02.02.2017 21:47:52] KSPI axAction (elene): reload_timeSheet
[02.02.2017 21:48:18] login: riaan as user

**Comment by kevinpapst** [comment] 2017-12-16 13:28
Sorry, this not reproducable for us. If you have further information we will have a look into it, but until then I can only close this as "works for me".

**Closed by kevinpapst** 2017-12-16 13:28 UTC
