### ISSUE TITLE
UI Changed With Change of Time Format.

### ISSUE THREAD

**Issue by ShahadatHossainRafi** [kimai/kimai#622] opened 2016-03-19 06:38 UTC
#### Expected behaviour
I edited extenstions/kiexport/init.php file to change date format from DD.MM to DD.MM.YYYY. However now I see table header is not showing properly with table column. You can see it here.. http://prnt.sc/ah4o4s. I just want to show the columns exactly underneath of every column header. From which file I can edit the HTML? Any help would be highly appreciated. 

#### Actual behaviour
Table headers are not showing over table columns.

#### Steps to reproduce the behaviour
I think the table is creating dynamically so changing the HTML would require changing in PHP/JavaScript codes too.

#### Kimai version
Latest version

**Comment by kevinpapst** [comment] 2016-03-19 10:22
The logic here is more complicated as the headers are not in the same table than the data.
The colum-width calculations are done in Javascript. The export extension needs to be rewritten and we are going to do that. Unfortunately, its far from simple...
Closing, as it is a duplicate of #105

**Closed by kevinpapst** 2016-03-19 10:22 UTC

**Comment by ShahadatHossainRafi** [comment] 2016-03-19 10:57
Ok thanks for the confirmation. Let me know once you fixed this. And I think It could be better if you use two separate programs for the UI and excel. In this way we could export year in excel spreadsheet but we can keep the default DD.MM format in the kimai UI.

**Comment by kevinpapst** [comment] 2016-03-19 13:00
BTW - did you try the date_format setting in the export extension itself? I mean the input text field in the upper middle part, when using the 3 button from the top-left.
Could that be what you want?

**Comment by ShahadatHossainRafi** [comment] 2016-03-20 14:01
Hi @kevinpapst Well I didn't notice it before. Thanks for the indication. Yes I was looking for this. But do you see how the columns are moving from underneath of each column header? This is where I think you can work to fix. :)

**Comment by kevinpapst** [comment] 2016-03-20 14:18
Yes I know what you mean. I already tried to fix that. Sounds easy ... to be honest, I know that. 
But it isn't. The person who develop it in the first hand, bounded a lot of Javascript to all the different columns in both header and table (which are in reality to separate tables).
That coupling is so complicated that I failed twice while trying to move everything into one HTML table - or lets say I gave up in the middle of the process.
I will for sure give it a try again, because you are not the first person to complain about it. And I don't like it as well. Its just a matter of time ;-)

**Comment by simonschaufi** [comment] 2016-03-20 22:04
something like this will probably help us:

- http://stackoverflow.com/questions/11499973/how-to-fixed-table-header-no-jquery
- https://css-tricks.com/persistent-headers/
- http://charliepark.org/css-only-sticky-headers/
- http://mkoryak.github.io/floatThead/
- https://github.com/jmosbech/StickyTableHeaders
- http://tympanus.net/Tutorials/StickyTableHeaders/
- http://tympanus.net/codrops/2014/01/09/sticky-table-headers-columns/

**Comment by engr-rafi** [comment] 2016-03-21 07:44
Hey @kevinpapst Thanks man for confirmation. Yes I tried it too but give up once I messed everything as because same problem. However once you done please give a reply here so that I can test the new interface and report back to you. :)

**Comment by ShahadatHossainRafi** [comment] 2016-03-21 08:17
Hey @kevinpapst Thanks man for confirmation. Yes I tried it too but give up once I messed everything as because same problem. However once you done please give a reply here so that I can test the new interface and report back to you. :)

**Comment by kevinpapst** [comment] 2016-03-25 21:57
Hey @ShahadatHossainRafi, thanks to your posting I tried it again and was lucky this time. The fix was merged into master just moments ago. So you can test now. Let me know if it works better for you now.
And I know that there could still be smaller problems with some translations (see my comments in #640), I just tested english and german.
