### ISSUE TITLE
Inconsistent user details on confirmation page

### ISSUE THREAD

**Issue by roskakori** [kimai/kimai#4754] opened 2024-04-08 13:44 UTC
### Describe the issue

Steps to reproduce (I used German language, maybe this is limited to this language).
1. Register a new cloud account
2. In the confirmation email, click the link
3. Wait until the cloud instance is created (took about 1 minute for me).

Actual result: The confirmation page shows my email and a password. Instead of the password, it shows the email again. (See screenshot)

Expected result: I'd be fine with only the email, or nothing. I would find it questionable if it actually shows the password here because someone might look over my shoulder.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.x (cloud)

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

Unknown

### Screenshots

![image](https://github.com/kimai/kimai/assets/328726/7429d707-9297-4a64-92ea-0460fdb41dfa)

**Comment by kevinpapst** [comment] 2024-04-08 14:02
Thanks for your feedback.
Not a bug though, your initial password is your email.
You should obviously change it after the first login.

And yes, the onboarding flow could be improved, I agree. Thanks for bringing it up 👍 

I am closing here, because this is the repo for the Kimai software, not the cloud. You can use the support are for that.

**Closed as completed by kevinpapst** 2024-04-08 14:02 UTC
Labels: bug

**Comment by roskakori** [comment] 2024-04-08 15:05
Oh, I understand.

That was a bit confusing because I already had an account with a working password. Which (of course) did not work anymore after signing up again. So I reset it and then could connect.

Everything works now, but it was confusing.

**Comment by kevinpapst** [comment] 2024-04-08 18:29
I know 👍  there is always room for improvement 😄
