### ISSUE TITLE
Question - is it possible to create activities which are available for every project?

### ISSUE THREAD

**Issue by aebner** [kimai/kimai#233] opened 2018-07-24 09:35 UTC
Hi,

we have many projects with similar activities and
don't want to create the same activities again and again.

As I remember in kimai v1 it was possible.
Is it possible in kimai v2 too?

Thank you

**Comment by kevinpapst** [comment] 2018-07-24 10:07
Not yet, I am thinking about changing that. 
Duplicate of https://github.com/kevinpapst/kimai2/issues/200

**Closed as completed by kevinpapst** 2018-07-24 10:07 UTC
Labels: duplicate, support
