### ISSUE TITLE
mysql_data_seek(): Offset 0 is invalid for MySQL

### ISSUE THREAD

**Issue by claude-ws01** [kimai/kimai#497] opened 2015-06-30 06:13 UTC
v0.9.3RC
file: core/libraries/mysql.class.php
function RecordsArray()

changed:
```
if ($this->last_result) {
```
to
```
if (mysql_num_rows($this->last_result) >= 1) {
```

**Comment by simonschaufi** [comment] 2015-07-05 23:35
this method is only called in the db_restore.php and updater.php, or? describing a way how to reproduce it would be great.

**Comment by cloudeasy** [comment] 2015-07-06 00:04
FIRST. you can read about it here:
http://stackoverflow.com/questions/4860152/offset-0-is-invalid-for-mysql-result-index-64-or-the-query-data-is-unbuffered

SECOND: "only called in the db_restore.php and updater.php". 

Simon, our exchange could really benefit from you doing your home work before writting. (this is the 2nd time you write without checking properly: https://github.com/kimai/kimai/issues/501)


For this time, see what I see:

Targets
    String 'RecordsArray('
Found usages  (34 usages found)
      (7 usages found)
        db_restore.php  (3 usages found)
            (79: 24) $tables = $conn->RecordsArray();
            (110: 24) $tables = $conn->RecordsArray();
            (229: 26) $tables = $conn->RecordsArray();
        updater.php  (4 usages found)
            (623: 32) $rows = $conn->RecordsArray(MYSQL_ASSOC);
            (728: 32) $rows = $conn->RecordsArray(MYSQL_ASSOC);
            (800: 32) $rows = $conn->RecordsArray(MYSQL_ASSOC);
            (872: 32) $rows = $conn->RecordsArray(MYSQL_ASSOC);
    extensions\ki_expenses  (3 usages found)
        private_db_layer_mysql.php  (3 usages found)
            (356: 20) $rows = $conn->RecordsArray(MYSQL_ASSOC);
            (402: 20) $rows = $conn->RecordsArray(MYSQL_ASSOC);
            (445: 20) $rows = $conn->RecordsArray(MYSQL_ASSOC);
    libraries  (2 usages found)
        mysql.class.php  (2 usages found)
            (1124: 18) return $this->RecordsArray($resultType);
            (1215: 18) public function RecordsArray($resultType = MYSQL_BOTH) {
    libraries\Kimai\Database  (22 usages found)
        Mysql.php  (22 usages found)
            (228: 28) $rows = $this->conn->RecordsArray(MYSQL_ASSOC);
            (491: 28) $rows = $this->conn->RecordsArray(MYSQL_ASSOC);
            (831: 28) $rows = $this->conn->RecordsArray(MYSQL_ASSOC);
            (865: 28) $rows = $this->conn->RecordsArray(MYSQL_ASSOC);
            (938: 28) $rows = $this->conn->RecordsArray(MYSQL_ASSOC);
            (963: 28) $rows = $this->conn->RecordsArray(MYSQL_ASSOC);
            (2057: 28) $rows = $this->conn->RecordsArray(MYSQL_ASSOC);
            (2976: 28) $rows = $this->conn->RecordsArray(MYSQL_ASSOC);
            (3000: 28) $rows = $this->conn->RecordsArray(MYSQL_ASSOC);
            (3135: 28) $rows = $this->conn->RecordsArray(MYSQL_ASSOC);
            (3386: 29) return $this->conn->RecordsArray(MYSQL_ASSOC);
            (3402: 27) return $this->conn->RecordsArray(MYSQL_ASSOC);
            (3465: 28) $rows = $this->conn->RecordsArray(MYSQL_ASSOC);
            (3539: 28) $rows = $this->conn->RecordsArray(MYSQL_ASSOC);
            (3612: 28) $rows = $this->conn->RecordsArray(MYSQL_ASSOC);
            (3685: 28) $rows = $this->conn->RecordsArray(MYSQL_ASSOC);
            (3866: 25) return $this->conn->RecordsArray(MYSQL_ASSOC);
            (4064: 25) return $this->conn->RecordsArray(MYSQL_ASSOC);
            (4340: 27) return $this->conn->RecordsArray(MYSQL_ASSOC);
            (4356: 28) $rows = $this->conn->RecordsArray(MYSQL_ASSOC);
            (4441: 27) return $this->conn->RecordsArray(MYSQL_ASSOC);
            (4457: 28) $rows = $this->conn->RecordsArray(MYSQL_ASSOC);

regards
c.

**Comment by simonschaufi** [comment] 2015-07-06 00:55
Thank you about the link.
Second: i mean the original call, not all the calls. I was tracing them back to the first call.

Generally it would be helpful to get a short description how to reproduce bugs. This should be included in a good bug report.

**Comment by cloudeasy** [comment] 2015-07-06 01:42
Generally I write very good and detailled description with nice 
printScreens when I am submitting a bug.

But I am not submitting a bug, I am informing you of the solution I have 
appied, after many hours of frustration navigating what I consider 
uneven lazy programming without any kind of standards.

Then I would have to write you a full fledge report!!!

Please... have a little humility, do your home work, and stop giving 
advices on what SHOULD be and what's GOOD.

**Comment by simonschaufi** [comment] 2015-07-06 10:34
> Generally I write very good and detailed description with nice printScreens when I am submitting a bug.

In this case I want to reproduce it and didn't know exactly how. That's why I was asking. Even if it is not a bug, I need to know WHY something needs to be changed.

> But I am not submitting a bug, I am informing you of the solution I have applied, after many hours of frustration

Thank you very much for investing so much time.

> lazy programming without any kind of standards.

please don't blame me for that, I'm just a team member since a few days.

> Please... have a little humility, do your home work

I can only do my homework if the task is clear. In your original report you don't give any information why this needs to be changed. What would you do in such a case somebody hands over this task to you?

**Comment by kevinpapst** [comment] 2015-07-06 11:23
Guys, please be kind :-) We all try to make the IT world a better place. Some by creating (or maintaining) an open source software, the other ones by helping out with bug reports and possible solutions.

@simonschaufi "I'm just a team member since a few days." ... don't blame the rest of the team for the code quality! Its just what it is: mostly working but crappy code ;-) 

@cloudeasy We took over Kimai from the original authors, who wanted to abandon and take down the project completely. So we are in the same boat here, we inherited a software which was written in a very, very poor style. We know that and suffer the same then you, while reasding through and working with the code ;-)
I know you want to help us out and really appreciate that, keep on doing that, great work! But @simonschaufi has a valid point here as well. Your first postings is missing any information on what is going on here. Your second clears it up, but you seem to be an IT guy as well. What would you do if you get a report like yours?

Lets work together and improve Kimai. Sadly there are no unit tests and if we change a central piece of code, it would be good to know the reason. Not just the link to Stackoverflow but also the original problem you faced while using Kimai.

**Comment by simonschaufi** [comment] 2016-06-19 22:11
Since it is not clear how to reproduce this issue, let's close it for now.

**Closed by simonschaufi** 2016-06-19 22:11 UTC
Labels: Bug
