### ISSUE TITLE
Google SSO after upgrade gives error

### ISSUE THREAD

**Issue by jzonthemtn** [kimai/kimai#4156] opened 2023-07-02 14:29 UTC
### Describe the issue

After upgrading from 1.x to 2.0.26, with Google SSO enabled, the following error is written to the log and 500 response is returned when trying to access.

```
php.CRITICAL: Uncaught Error: App\Configuration\SamlConfiguration::getProvider(): Return value must be of type string, null returned {"exception":"[object] (TypeError(code: 0): App\\Configuration\\SamlConfiguration::getProvider(): Return value must be of type string, null returned at /var/www/kimai2/src/Configuration/SamlConfiguration.php:30)"} []
[2023-07-02T14:26:07.170124+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "App\Configuration\SamlConfiguration::getProvider(): Return value must be of type string, null returned" at /var/www/kimai2/src/Configuration/SamlConfiguration.php line 30 {"exception":"[object] (TypeError(code: 0): App\\Configuration\\SamlConfiguration::getProvider(): Return value must be of type string, null returned at /var/www/kimai2/src/Configuration/SamlConfiguration.php:30)"} []
```

Disabling SSO allows local logins to 2.0.26 fine. (Google SSO was working with 1.x prior to the upgrade.)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.26

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Logfile

```
php.CRITICAL: Uncaught Error: App\Configuration\SamlConfiguration::getProvider(): Return value must be of type string, null returned {"exception":"[object] (TypeError(code: 0): App\\Configuration\\SamlConfiguration::getProvider(): Return value must be of type string, null returned at /var/www/kimai2/src/Configuration/SamlConfiguration.php:30)"} []
[2023-07-02T14:26:07.170124+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "App\Configuration\SamlConfiguration::getProvider(): Return value must be of type string, null returned" at /var/www/kimai2/src/Configuration/SamlConfiguration.php line 30 {"exception":"[object] (TypeError(code: 0): App\\Configuration\\SamlConfiguration::getProvider(): Return value must be of type string, null returned at /var/www/kimai2/src/Configuration/SamlConfiguration.php:30)"} []
```

**Comment by kevinpapst** [comment] 2023-07-02 17:07
Read the docs or use the search, this has been discussed multiple times already.

**Comment by kevinpapst** [comment] 2023-07-02 17:08
Duplicate of #4130

**Closed as completed by kevinpapst** 2023-07-02 17:07 UTC
Labels: bug, duplicate

**Comment by jzonthemtn** [comment] 2023-07-02 20:21
> Read the docs or use the search, this has been discussed multiple times already.

My apologies, but I don't see anything in the docs at https://www.kimai.org/documentation/saml-google.html or the [Upgrading](https://github.com/kimai/kimai/blob/main/UPGRADING.md) guide that mentioned the issue.
