### ISSUE TITLE
Activity on project with fixed rate is not correctly saved on timesheet

### ISSUE THREAD

**Issue by juhamoisio** [kimai/kimai#814] opened 2016-08-30 06:47 UTC
#### Expected behaviour

When user without permission to see amounts creates entry on timesheet using activity with fixed rate set on project, correct amount is not saved. 
#### Actual behaviour

Fixed rate from activity project tab should be saved with entry. 
#### Steps to reproduce

Create activity and set it to project and set fixed rate. Then create entry to timesheet using that activity
#### Reproducable on demo.kimai.org? [yes|no]

Yes

**Comment by simonschaufi** [comment] 2016-08-30 08:44
Is this the same issue that you mean that has been fixed in develop already? #807

**Comment by juhamoisio** [comment] 2016-08-30 08:49
No I dont think so cause I have activity assign to group and there is fixed rate set.
When normal user creates timesheet entry using that activity amount will be zero.

**Comment by simonschaufi** [comment] 2016-08-30 10:17
So you think it is a permission thing? Can you please make the relevant screenshot of your permissions set? Does this problem also occur for admin users?

**Comment by juhamoisio** [comment] 2016-08-31 05:39
yes it happens also to admin user. even if the correct value is in then fixed rate field on budget tab amount is zero or if you just select that activity and do not touch fixed rate field then entry may be saved using default rate as hours... which is not correct behavior in my opinion

**Comment by simonschaufi** [comment] 2016-09-01 22:21
Can you add some screenshots? I don't really understand your problem (and I can't reproduce it)

**Comment by juhamoisio** [comment] 2016-09-02 05:44
![kimai1](https://cloud.githubusercontent.com/assets/2642046/18193782/736cd3dc-70e9-11e6-9aed-819d8cc77ebc.png)
![kimai2](https://cloud.githubusercontent.com/assets/2642046/18193783/736d8a5c-70e9-11e6-8ef6-582d835f7840.png)
![kimai3](https://cloud.githubusercontent.com/assets/2642046/18193784/736e9488-70e9-11e6-99c7-a55374f417ea.png)
![kimai4](https://cloud.githubusercontent.com/assets/2642046/18193781/736b4166-70e9-11e6-9d36-f5553b78e0d3.png)
![kimai5](https://cloud.githubusercontent.com/assets/2642046/18193780/736b2a32-70e9-11e6-8b87-bbc38cfe33b8.png)

**Comment by kevinpapst** [comment] 2016-09-02 07:34
Hm, how much do you expect for a duration of 0? From what I learned in school 0 * X is always 0 ;-)

**Comment by simonschaufi** [comment] 2016-09-02 08:41
Well, when you set a fixed rate, no matter how long you work, it will be 20 in this case which works on demo when you start the timer.
Right, when you add an entry manually it doesn't. That needs to be fixed.

**Comment by juhamoisio** [comment] 2016-09-02 09:01
But there is fixed rate.

**Comment by kevinpapst** [comment] 2016-09-02 10:26
Sorry, didn't read it correctly ;-)

**Comment by kevinpapst** [comment] 2021-04-18 15:46
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).

**Closed by kevinpapst** 2021-04-18 15:46 UTC
Labels: Bug
