### ISSUE TITLE
In released beta and latest SVN build, invoice shows UNIX style dates...

### ISSUE THREAD

**Issue by alauppe** [kimai/kimai#284] opened 2013-11-21 12:24 UTC
...instead of strftim() formatted dates

I have the date format set to %m-%d everywhere. Before my upgrade (from 0.8 I believe) invoices had the proper date, but now, today for example, looks like 1385036389.

Thanks!

**Comment by ServiusHack** [comment] 2015-01-26 22:09
You were both right, the issue is still not fixed. I actually broke it again in f5b4790f9fe16d159adc6cc2a104cc1d5543a241 which was the only change between my original fix and now.

So with #458 I've performed the fix again. First, it must be "frm" and not "fmt". Second, there must be no formatting instructions for everything from the opening bracket to the closing one.

You can check for the formatting instructions by opening the odt file using some ZIP unpacker and then opening the contained content.xml file. Searching for "today" should show the whole formatting statement without any XML-Elements in between.

**Closed** 2015-01-26 22:13 UTC
Labels: Bug
