### ISSUE TITLE
Tooltip When filling the record

### ISSUE THREAD

**Issue by sachinragul** [kimai/kimai#5177] opened 2024-11-25 04:30 UTC
### Describe the issue

Go to calendar and click on dates to fill the record. Sometimes tooltip (on hover of record) appears while filling the record.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.16.1

### How do you run Kimai?

Docker

### Which PHP version are you using?

Unknown

### Screenshots

![samaya1](https://github.com/user-attachments/assets/4926ef2d-fc4b-452d-bb8a-47cdeacda604)

**Comment by kevinpapst** [comment] 2024-11-25 16:19
Duplicate of #4880 - please share your experiences there. Especially reliable ways to reproduce this bug are interesting!

**Closed as not planned by kevinpapst** 2024-11-25 16:19 UTC
Labels: bug, duplicate, calendar

**Comment by Raistlin707** [comment] 2024-12-02 15:51
Hi,
One way to reproduce it quite easily:
1 : Click on a date from the calendar
2 : Fill and save the record
3 : Upon saving, the "create" form will disappear. If your mouse pointer hovers over a date and triggers a tooltip at the same time : that tooltip may freeze.

Tested with both "create" and "modify" forms, Chrome and Firefox, on Xubuntu 22.04. Same problem everywhere.

Note: Tooltips appear to stack if the mouse hovers over the same date with one or more frozen tooltips.

![image](https://github.com/user-attachments/assets/8836c90e-ad56-49d9-86f6-137d18661529)

![image](https://github.com/user-attachments/assets/f3b95c2e-f879-4ed7-b50b-794666ec8c2c)
