### ISSUE TITLE
Email in HTML Invoice Template shows a "email protected" when invoice is downloaded

### ISSUE THREAD

**Issue by buti1021** [kimai/kimai#5245] opened 2024-12-17 21:08 UTC
### Describe the issue

When I want to download an invoice I created with the HTML Invoice template, the email is not shown, but instead the text "[email protected]"
![image](https://github.com/user-attachments/assets/04e94459-536c-4df6-a3af-b5a3bcffe194)

When I open the invoice as preview during invoice creation the email is properly shown

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.26

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

Version 8.3

**Comment by kevinpapst** [comment] 2024-12-18 17:03
Cannot reproduce, closing.

Try another browser maybe. Or use PDF template instead.

**Closed as not planned by kevinpapst** 2024-12-18 17:03 UTC
Labels: bug
