### ISSUE TITLE
Kimai Holdiay issue.

### ISSUE THREAD

**Issue by Peanut1906** [kimai/kimai#4483] opened 2023-12-06 08:28 UTC
### Describe the issue

Hey, we are having the problem that Holidays are not calculated based on when an employee starts. For a new employee starts he/she will always get a fixedamount of Holidays for the rest of the year. My question: isn't there an option to make the Holidays be calculated based on when he/she starts working. If an employee starts in october it would be great if he only received 7 days of vacation instead of 28. I don't know if that is a bug or a missing feature but it would be incredibly helpful for us. 

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

Unknown

### Screenshots

<img width="344" alt="Screenshot 2023-12-06 092255" src="https://github.com/kimai/kimai/assets/94468372/9cf1bb51-936d-4616-a83c-c7aead34c0c8">

**Comment by kevinpapst** [comment] 2023-12-06 09:26
Hi 👋 thanks for sharing your thoughts.

1. This is not a bug.
2. This is a "german" problem or at least depends on the country of origin. In Austria for example holidays are counted from the day of entry.

> it would be incredibly helpful for us 

I always wonder about the workflow when such phrases are used: how many employees do you on- and offboard, that changing the holidays after the 01 Jan. for new employees is such a huge challenge?

Yes, I do plan to add support at some point. But adding such a feature requires to build custom rules for many countries, which isn't easy (especially from a legal perspective). 

I am closing, becuase this repository is about Kimai itself.

You can post this in the repository dedicated to Paid plugins at: https://github.com/kevinpapst/kimai-plugins

And I will add your wish to the ideas list.

**Closed as completed by kevinpapst** 2023-12-06 09:26 UTC
Labels: feature request, plugin
