### ISSUE TITLE
Internal Rate set at user profile not flowing to project

### ISSUE THREAD

**Issue by TGG-RPA** [kimai/kimai#3816] opened 2023-02-04 03:28 UTC
### Describe the issue

This seems related to the below issue:
[https://github.com/kimai/kimai/issues/2181]

To replicate the behaviour:

1. Set an internal rate for a given user profile - say, Resource A @ $100 / hour
2. Proceed to assign Resource A to Project 1
3. Under Project 1, create a rate for Resource A by specifying the Hourly Rate to be $200 / hour but leave Internal Rate blank
4. Expectation is that since the Internal Rate is blank, it should default to $100 / hour per step 1
5. However, it defaults to $200 / hour instead

While offering additional flexibility the specify Hourly Rate and Internal Rate per resource at the Project level, when the Internal Rate is "Null", why isn't it pulling the default Internal Rate specified on the Resource?

If this is designed as intended, it creates administrative burden and challenges in maintaining rate consistency.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.5 (self hosted)

### How do you run Kimai?

Other (please mention below)

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment] 2023-02-04 16:52
Works as expected. But the implementation seems to be naive and causes friction. It is planned to change that behavior. 
But it is a duplicate of #3697 => So I close here. Leave your vote there please.

**Closed as completed by kevinpapst** 2023-02-04 16:52 UTC
Labels: bug, duplicate
