### ISSUE TITLE
Mark timesheets as exported after invoice was created

### ISSUE THREAD

**Issue by theprofilinglabs** [kimai/kimai#389] opened 2018-11-05 13:18 UTC
**Is your feature request related to a problem? Please describe.**
This is not related to a problem. This is related to our current use of Kimai (currently i 1.1.0.1389 ) and determining whether we should consider moving to the new version you are working on . 
I have tried the demo version and been through the documentation available so far. The new version looks great - really nice look and feel and we like it a lot.

Having been through the documentation and run the demo, it seems a key part of the functionality we use in our current version is not available.

Currently our office team use the filtering in our version to filter time sheets by projects, and then export them to a csv file - as you know this then changes the status of entries as they are exported, meaning the next time they export there is no duplication of records already exported into the export file.

**Describe the solution you'd like**

Include project column in the options for the Team timesheet view 
https://demo-v2.kimai.org/en/team/timesheet/

INclude PROJECTS in the filtering facilities for timesheet entries - ( sorry about the pic!!) 

![image](https://user-images.githubusercontent.com/6179020/47999960-0c725500-e0fc-11e8-91d4-d2ebe9b84789.png)

Exporting of selected columns into a spreadsheet , csv etc , using the same filtering as the Team timesheet view and including projects as an output option .

Records exported have a status change - export criteria allows selection o f "All" or "Active" records

**Comment by kevinpapst** [comment] 2018-11-05 20:33
Thanks for your feedback!

1. The timesheet view is exclusively meant for each user. Exporting data here is only meant for the user himself. 

2. Team timesheet view is only meant for administration of timesheet entries. This view should not be used for exporting. Your office team will have to adapt the current workflow slightly when migrating from v1. 

3. If you want to export data, this is always done through the "invoice" tab. Yes, the wording "invoice" is probably a bit misleading here. Export options for CSV are existing, if you need it. You might have to create a new invoice template if you need different columns, see https://github.com/kevinpapst/kimai2/blob/master/var/docs/invoices.md
There is no "click columns to export" view for now. If that is crucial for you, please create a new feature request for it. Using your own invoice document should be safer, as then there is no way of manual errors.

4. User and team timesheet can be filtered by project, you just have to select the customer first, then the project filter will show up. The UI needs improvements (e.g. the filters should be shown after reload), please open a new feature request if you want to this to be improved sooner than later.

5. Can you elaborate on `Records exported have a status change - export criteria allows selection o f "All" or "Active" records`? What exactly do you mean by that? Active record (running timesheet entries) shouldn't be allowed for exporting.

6. I will treat the last point as feature request: having a flag on each timesheet record, that it was already exported. I guess that I will add a new button to the invoice view, which will show up after the invoice "print" button was used.

**Comment by kevinpapst** [comment] 2018-11-07 23:49
The feature request is a duplicate of #373 
If you have further feedback on my answers, simply post them. Otherwise I will close this issue by the end of the week.

**Closed as completed** 2018-11-10 16:21 UTC
Labels: duplicate, support, invoice
